export { default as MenuIcon } from "./MenuIcon"
export { default as LoadingIcon } from "./LoadingIcon"

export { default as CSS3Icon } from "./CSS3Icon"
export { default as HTML5Icon } from "./HTML5Icon"
export { default as SassIcon } from "./SassIcon"
export { default as JSIcon } from "./JSIcon"
export { default as ReactIcon } from "./ReactIcon"
export { default as NextJSIcon } from "./NextJSIcon"
export { default as MongoDBIcon } from "./MongoDBIcon"
export { default as NodeJSIcon } from "./NodeJSIcon"
export { default as GitIcon } from "./GitIcon"
export { default as PhotoshopIcon } from "./PhotoshopIcon"
export { default as IllustratorIcon } from "./IllustratorIcon"
export { default as FigmaIcon } from "./FigmaIcon"
export { default as GithubIcon } from "./GithubIcon"
export { default as LinkedInIcon } from "./LinkedInIcon"
export { default as CodePenIcon } from "./CodePenIcon"